name: CI

on: 
  push:
    branches: 
      - master
      - develop


env:
  CI: true

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Setup Ionic
        uses: coturiv/setup-ionic@v1

      - name: Install dependencies
        run: npm ci

      - name: Build apk
        run: ionic cordova build android

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: app-debug
          path: ./platforms/android/app/build/outputs/apk/debug/app-debug.apk 
